name: geopandas
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - blas=1.0
  - blosc=1.21.6
  - boost-cpp=1.85.0
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - capnproto=1.0.2
  - cffi=1.17.1
  - cfitsio=4.5.0
  - charset-normalizer=3.4.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - expat=2.6.4
  - fmt=11.0.2
  - folium=0.19.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.10.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.3
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.82.2
  - glib-tools=2.82.2
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.5
  - joblib=1.4.2
  - json-c=0.18
  - kealib=1.6.0
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libavif16=1.1.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgdal=3.10.0
  - libgdal-core=3.10.0
  - libgdal-fits=3.10.0
  - libgdal-grib=3.10.0
  - libgdal-hdf4=3.10.0
  - libgdal-hdf5=3.10.0
  - libgdal-jp2openjpeg=3.10.0
  - libgdal-kea=3.10.0
  - libgdal-netcdf=3.10.0
  - libgdal-pdf=3.10.0
  - libgdal-pg=3.10.0
  - libgdal-postgisraster=3.10.0
  - libgdal-tiledb=3.10.0
  - libgdal-xls=3.10.0
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.32.0
  - libgoogle-cloud-storage=2.32.0
  - libgrpc=1.67.1
  - libheif=1.18.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libopenblas=0.3.21
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - minizip=4.0.7
  - munkres=1.1.4
  - ncurses=6.5
  - nspr=4.35
  - nss=3.105
  - openjpeg=2.5.2
  - openldap=2.6.9
  - openssl=3.4.0
  - pcre2=10.44
  - pixman=0.44.2
  - poppler=24.08.0
  - poppler-data=0.4.11
  - postgresql=17.2
  - proj=9.5.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.1
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rtree=1.3.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - snappy=1.2.1
  - spdlog=1.14.1
  - sqlite=3.47.2
  - svt-av1=2.3.0
  - threadpoolctl=3.5.0
  - tiledb=2.27.0
  - tk=8.6.13
  - tzcode=2024b
  - uriparser=0.9.8
  - urllib3=2.3.0
  - wheel=0.44.0
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - alphashape==1.3.1
      - altgraph==0.17.4
      - appnope==0.1.4
      - asttokens==3.0.0
      - cartopy==0.23.0
      - certifi==2024.7.4
      - click==8.1.7
      - click-log==0.4.0
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fonttools==4.53.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.4
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - macholib==1.16.3
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - narwhals==1.42.1
      - nest-asyncio==1.6.0
      - network==0.1
      - networkx==3.2.1
      - numpy==2.0.1
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==24.3.1
      - platformdirs==4.3.6
      - plotly==6.1.2
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyinstaller==6.12.0
      - pyinstaller-hooks-contrib==2025.2
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyshp==2.3.1
      - pyyaml==6.0.2
      - setuptools==75.6.0
      - shapely==2.0.5
      - six==1.16.0
      - stack-data==0.6.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - trimesh==4.5.2
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - wcwidth==0.2.13
      - zipp==3.20.0
